### ISSUE TITLE
[BUG] Wrong link in "What Git is and how we use it"

### ISSUE THREAD

**Issue by eric-asam22** [rollyourown-xyz/ryo-website-content#1]
**Content bug description**
Please add a short description of the content bug.
The Link is not correct under Pull request "This procedure is described in more detail [here](http://localhost:1313/collaborate/working_with_git/forking_and_pull_requests/)." 
I think it should be. https://rollyourown.xyz/collaborate/working_with_git/forking_and_pull_requests

**Link to website**
Please add a link to the page on [our website](https://rollyourown.xyz) containing the content bug.
https://rollyourown.xyz/collaborate/working_with_git/what_is_git/

https://rollyourown.xyz/collaborate/working_with_git/forking_and_pull_requests

**Section title**
Please tell us where on the page to find the content bug.
Pull request 

**Link to content in our repository**
If possible, please add a link to the content page in [our repository](https://github.com/rollyourown-xyz/ryo-website-hugo-content).
https://rollyourown.xyz/collaborate/working_with_git/forking_and_pull_requests

**Expected content**
Please add a short description of what needs to be changed.
https://rollyourown.xyz/collaborate/working_with_git/forking_and_pull_requests

**Additional information**
Please add any other information to help us assess the content bug.

**Comment by xyzroller** [comment]
Yes, indeed, this is a copy-paste error where absolute links were copied instead of relative links.
Fixed now, also in a couple of other places, thank you.
